name: Azure Container Apps

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests with coverage
        run: dotnet test --no-build --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./coverage/

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
        
      - name: Generate HTML report
        run: |
          reportgenerator -reports:Tests/TestResults/*/coverage.cobertura.xml -targetdir:./coverage_report -reporttypes:Html

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./coverage_report

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
        run: echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
